[2025-06-20 13:15:37] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:37] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:38] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:38] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:39] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:39] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:40] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:40] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:41] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:41] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:42] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:42] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:43] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:43] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:44] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:44] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:45] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:45] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:46] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:46] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:47] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:47] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:48] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:48] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:15:49] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:16:59] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:16:59] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:00] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:00] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:01] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:01] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:02] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:02] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:03] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:03] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:04] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:04] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:05] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:05] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:06] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:06] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:07] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:07] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:08] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:08] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:09] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:09] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:10] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:10] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:11] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:11] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:12] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:12] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:13] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:13] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:14] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:14] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:15] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:15] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:16] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:16] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:17] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:17] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:18] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:18] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:19] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:19] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:20] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:20] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:21] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:21] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:22] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:22] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:23] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:23] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:24] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:24] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:25] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:25] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:26] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:26] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:27] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:27] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:28] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:28] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:29] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:29] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:30] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:30] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:31] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu14", line 1665, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:34] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:34] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:35] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:35] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:36] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:36] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:37] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:37] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:38] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:38] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:39] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:39] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:40] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:40] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:41] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:41] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:42] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:42] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:43] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:43] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:44] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:44] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:45] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:45] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:46] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:46] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:47] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:47] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:48] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:48] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:49] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:49] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:50] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:50] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:51] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:51] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:52] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:52] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:53] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:53] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:54] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:54] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:55] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:55] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:56] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:56] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:57] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:57] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:58] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:58] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:59] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:17:59] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:00] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:00] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:01] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:01] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:02] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:02] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:03] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:03] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:04] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:04] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:05] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:05] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:06] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:06] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:07] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:07] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:08] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:08] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:09] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:09] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:10] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:10] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:11] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:11] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:12] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:12] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:13] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:13] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:14] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:14] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:15] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:15] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:16] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:16] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:17] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:17] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:18] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:18] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:19] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:19] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:20] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:20] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:21] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:21] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:22] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:22] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:23] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:23] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:24] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:24] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:25] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:25] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:26] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:26] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:27] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:27] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:28] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:28] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:29] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:29] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:30] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:30] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:31] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:31] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:32] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:32] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:33] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:33] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:34] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:34] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:35] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:35] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:36] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:36] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:37] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:37] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:38] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:38] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:39] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:39] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:40] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:40] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:41] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:41] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:42] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:42] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:43] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:43] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:44] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:44] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:45] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:45] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:46] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:46] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:47] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:47] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:48] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:48] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:49] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:49] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:50] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:50] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:51] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:51] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:52] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:52] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:53] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:53] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:54] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:54] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:55] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:55] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:56] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:56] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:57] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:57] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:58] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:59] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:18:59] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:00] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:00] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:01] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:01] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:02] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:02] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:03] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:03] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:04] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:04] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:05] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:05] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:06] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:06] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:07] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:07] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:08] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:08] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:09] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:09] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:10] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:10] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:11] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:11] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:12] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:12] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:13] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:13] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:14] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:14] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:15] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:15] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:16] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:16] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:17] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:17] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:18] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:18] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:19] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:19] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:20] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:20] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:21] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:21] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:22] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:22] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:23] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:23] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:24] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:24] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:25] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:25] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:26] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:26] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:27] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:27] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:28] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:28] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu13", line 1668, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:31] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:32] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:32] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:33] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:33] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:34] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:34] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:35] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:35] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:36] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:36] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:37] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:37] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:38] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:38] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:39] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:39] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:40] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:40] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:41] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:41] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:42] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:42] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:43] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:43] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:44] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:44] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:45] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:45] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:46] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:46] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:47] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:47] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:48] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:48] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:49] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:49] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:50] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:51] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:52] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:52] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

[2025-06-20 13:19:53] Exception in status_screen:
Traceback (most recent call last):
  File "/home/brian/DRX/backups/7/drx_main.py-bu12", line 1629, in status_screen
    stdscr.addstr(y, 0, line, curses.color_pair(6) | curses.A_BOLD)
_curses.error: addwstr() returned ERR

